CREATE TABLE LOGIN_USER_TOKEN (
  id_lut BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
  token VARCHAR(50),    
  id_lur BIGINT,
  CONSTRAINT fk_LoginUserLoginUserToken FOREIGN KEY (id_lur)
  REFERENCES LOGIN_USER(id_lur)  
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci
