CREATE TABLE LOGIN_USER (
  id_lur BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  password BLOB NOT NULL,
  isAdmin TINYINT(1) NOT NULL DEFAULT 0,
  deleted BIT NOT NULL DEFAULT 0
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

