CREATE TABLE LOGS (    
    USER_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DATED   VARCHAR(50) NOT NULL,
    LOGGER  VARCHAR(255) NOT NULL,
    LEVEL   VARCHAR(10) NOT NULL,
    MESSAGE VARCHAR(1000) NOT NULL
)
